package nsbm.FRAMES.PostgraduateFrame.Business_school;



import javax.swing.JOptionPane;
import nsbm.FRAMES.HomeFrames.Home;
import nsbm.objects.Person;
import nsbm.objects.Student;
import nsbm.objects.Postgraduate;
import nsbm.objects.DBoperation;
/**
 *
 * @author ubandara
 */
public class postgraduate_SB_student extends javax.swing.JFrame {
    
    DBoperation db = new DBoperation();
    /**
     * Creates new form Registration
     */
    public postgraduate_SB_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comfirm = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        details = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        f_name = new javax.swing.JLabel();
        m_name = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        bdate = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        reg_no = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        q_type = new javax.swing.JLabel();
        institute = new javax.swing.JLabel();
        complete_year = new javax.swing.JLabel();
        phone_no = new javax.swing.JLabel();
        getFname = new javax.swing.JTextField();
        getMname = new javax.swing.JTextField();
        getLname = new javax.swing.JTextField();
        getNic = new javax.swing.JTextField();
        getBdate = new javax.swing.JTextField();
        getAge = new javax.swing.JTextField();
        getPnum = new javax.swing.JTextField();
        getRnum = new javax.swing.JTextField();
        getEmail = new javax.swing.JTextField();
        getQtype = new javax.swing.JTextField();
        getInstitute = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        address = new javax.swing.JLabel();
        add_line1 = new javax.swing.JLabel();
        add_line2 = new javax.swing.JLabel();
        add_line3 = new javax.swing.JLabel();
        getAline1 = new javax.swing.JTextField();
        getAline2 = new javax.swing.JTextField();
        getAline3 = new javax.swing.JTextField();
        regYear = new javax.swing.JLabel();
        semester = new javax.swing.JLabel();
        getRyear = new javax.swing.JTextField();
        getsem = new javax.swing.JTextField();
        courseId2 = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        getCourceId = new javax.swing.JTextField();
        getCSub1 = new javax.swing.JTextField();
        getCSub2 = new javax.swing.JTextField();
        getCSub3 = new javax.swing.JTextField();
        getCSub4 = new javax.swing.JTextField();
        getGender = new javax.swing.JTextField();
        getCyear = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        toback = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        comfirm.setTitle("comfirmation");
        comfirm.setLocation(new java.awt.Point(500, 300));
        comfirm.setMinimumSize(new java.awt.Dimension(803, 403));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT  REGISTRATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        jLabel1.setText("REGISTRATION SUCCESSFULLY DONE!!");

        ok.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ok)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout comfirmLayout = new javax.swing.GroupLayout(comfirm.getContentPane());
        comfirm.getContentPane().setLayout(comfirmLayout);
        comfirmLayout.setHorizontalGroup(
            comfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comfirmLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        comfirmLayout.setVerticalGroup(
            comfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comfirmLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");

        heading.setBackground(java.awt.Color.darkGray);
        heading.setFont(new java.awt.Font("Lato", 1, 80)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("NSBM GREEN UNIVERSITY");

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/index.png"))); // NOI18N

        details.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Light", 1, 20))); // NOI18N

        name.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        name.setText("Name");

        f_name.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        f_name.setText("First Name");

        m_name.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        m_name.setText("Middle Name");

        l_name.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        l_name.setText("Last Name");

        nic.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        nic.setText("NIC");

        bdate.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        bdate.setText("Birth Date");

        age.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        age.setText("Age");

        gender.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        gender.setText("Gender");

        reg_no.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        reg_no.setText("Registration No.");

        email.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        email.setText("Email");

        q_type.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        q_type.setText("Qulification Type");

        institute.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        institute.setText("Institute");

        complete_year.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        complete_year.setText("Year of Completion");

        phone_no.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        phone_no.setText("Phone No");

        getFname.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getFname.setText("first name");
        getFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getFnameFocusLost(evt);
            }
        });

        getMname.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getMname.setText("middle name");
        getMname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getMnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getMnameFocusLost(evt);
            }
        });

        getLname.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getLname.setText("last name");
        getLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getLnameFocusLost(evt);
            }
        });

        getNic.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getNic.setText("eg:- 983150350v");
        getNic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getNicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getNicFocusLost(evt);
            }
        });

        getBdate.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getBdate.setText("yyyy-mm-dd");
        getBdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getBdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getBdateFocusLost(evt);
            }
        });

        getAge.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getAge.setText("age");
        getAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAgeFocusLost(evt);
            }
        });

        getPnum.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getPnum.setText("eg:- 07x- xxxxxxx");
        getPnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getPnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getPnumFocusLost(evt);
            }
        });

        getRnum.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getRnum.setText("eg:- 2018pcs001");
        getRnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getRnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getRnumFocusLost(evt);
            }
        });

        getEmail.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getEmail.setText("yourmail@yourmail.com");
        getEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getEmailFocusLost(evt);
            }
        });

        getQtype.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        getInstitute.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        submit.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        address.setText("Address");

        add_line1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        add_line1.setText("Line 1");

        add_line2.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        add_line2.setText("Line 2");

        add_line3.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        add_line3.setText("Line 3");

        getAline1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getAline1.setText("line 1");
        getAline1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAline1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAline1FocusLost(evt);
            }
        });

        getAline2.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getAline2.setText("line 2");
        getAline2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAline2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAline2FocusLost(evt);
            }
        });

        getAline3.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getAline3.setText("line 3");
        getAline3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAline3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAline3FocusLost(evt);
            }
        });
        getAline3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAline3ActionPerformed(evt);
            }
        });

        regYear.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        regYear.setText("Reg. Year");
        regYear.setToolTipText("");

        semester.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        semester.setText("Semester");

        getRyear.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getRyear.setText("year");
        getRyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getRyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getRyearFocusLost(evt);
            }
        });

        getsem.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getsem.setText("eg:- 2018sem01");
        getsem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getsemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getsemFocusLost(evt);
            }
        });

        courseId2.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        courseId2.setText("Course Id");

        subject.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        subject.setText("Subjects Id");

        getCourceId.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCourceId.setText("eg:-Mas001");
        getCourceId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCourceIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCourceIdFocusLost(evt);
            }
        });

        getCSub1.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub1.setText("eg:- PS001");
        getCSub1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub1FocusLost(evt);
            }
        });

        getCSub2.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub2.setText("eg:- PS001");
        getCSub2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub2FocusLost(evt);
            }
        });

        getCSub3.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub3.setText("eg:- PS001");
        getCSub3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub3FocusLost(evt);
            }
        });

        getCSub4.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub4.setText("eg:- PS001");
        getCSub4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub4FocusLost(evt);
            }
        });

        getGender.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        getGender.setText("eg:- male");
        getGender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getGenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getGenderFocusLost(evt);
            }
        });

        getCyear.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout detailsLayout = new javax.swing.GroupLayout(details);
        details.setLayout(detailsLayout);
        detailsLayout.setHorizontalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsLayout.createSequentialGroup()
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m_name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(q_type, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(institute, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(complete_year, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(getMname)
                            .addComponent(getFname)
                            .addComponent(getLname)
                            .addComponent(getNic)
                            .addComponent(getBdate)
                            .addComponent(getAge)
                            .addComponent(getPnum)
                            .addComponent(getRnum)
                            .addComponent(getQtype)
                            .addComponent(getInstitute)
                            .addComponent(getGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(getEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(getCyear))
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detailsLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(add_line1)
                                    .addComponent(add_line2)
                                    .addComponent(add_line3))
                                .addGap(52, 52, 52)
                                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getAline1)
                                    .addComponent(getAline2)
                                    .addComponent(getAline3)))
                            .addGroup(detailsLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(getCSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(detailsLayout.createSequentialGroup()
                                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(getsem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(detailsLayout.createSequentialGroup()
                                            .addComponent(regYear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(getRyear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(detailsLayout.createSequentialGroup()
                                            .addComponent(courseId2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(getCourceId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(detailsLayout.createSequentialGroup()
                                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(getCSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(getCSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getCSub4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(address)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        detailsLayout.setVerticalGroup(
            detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f_name)
                    .addComponent(getFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_line1)
                    .addComponent(getAline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_name)
                    .addComponent(getMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_line2)
                    .addComponent(getAline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_name)
                    .addComponent(getLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_line3)
                    .addComponent(getAline3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nic)
                    .addComponent(getNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdate)
                    .addComponent(getBdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(getAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(regYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getRyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone_no)
                    .addComponent(getPnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg_no)
                    .addComponent(getRnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q_type)
                            .addComponent(getQtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(institute))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getCyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(complete_year))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(detailsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email)
                            .addComponent(courseId2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getCourceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getCSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE))))
        );

        home.setBackground(java.awt.Color.gray);
        home.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/home.png"))); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        toback.setBackground(java.awt.Color.gray);
        toback.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        toback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/back.png"))); // NOI18N
        toback.setText("BACK");
        toback.setMaximumSize(new java.awt.Dimension(160, 45));
        toback.setMinimumSize(new java.awt.Dimension(160, 45));
        toback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tobackActionPerformed(evt);
            }
        });

        logout.setBackground(java.awt.Color.gray);
        logout.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/logout.png"))); // NOI18N
        logout.setText("LOG OUT");
        logout.setMaximumSize(new java.awt.Dimension(160, 45));
        logout.setMinimumSize(new java.awt.Dimension(160, 45));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toback, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pic1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(heading)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
            Person P = new Person();
            Student stu1 = new Student();
            Postgraduate ps1 = new Postgraduate();
        
            ps1.setfName(getFname.getText());
            ps1.setmName(getMname.getText());
            ps1.setlName(getLname.getText());
            ps1.setAge(Integer.parseInt(getAge.getText()));
            ps1.setNic(getNic.getText());
            ps1.setBday(getBdate.getText());
            ps1.setSex(getGender.getText());
            ps1.setRegNo(getRnum.getText());
            ps1.setEmail(email.getText());
            ps1.setQualification(getQtype.getText());
            ps1.setSemester(getsem.getText());
            ps1.setAddressL1(getAline1.getText());
            ps1.setAddressL2(getAline1.getText());
            ps1.setAddressL3(getAline1.getText());
            ps1.setInstitute(getInstitute.getText());
            ps1.setRegYear(getRyear.getText());
            ps1.setYear(getCyear.getText());
            ps1.setPhone(getPnum.getText());
            ps1.setCourseId(getCourceId.getText());
            ps1.setFacId("nsbm02");
            ps1.setSubId1(getCSub1.getText());
            ps1.setSubId2(getCSub2.getText());
            ps1.setSubId3(getCSub3.getText());
            ps1.setSubId4(getCSub4.getText());
        
        
            db.addPostgraduate(ps1);
   
            comfirm.setVisible(true);
            
        }catch(Exception e){JOptionPane.showMessageDialog(null, "registration failed!!!", "_warning_", JOptionPane.WARNING_MESSAGE);}    
    }//GEN-LAST:event_submitActionPerformed

    private void getAline3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAline3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getAline3ActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        //
        postgraduate_SB_student_details p = new postgraduate_SB_student_details();
        p.setVisible(true);
        this.dispose();
        comfirm.dispose();
    }//GEN-LAST:event_okActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TO home
        Business_pg_login a =new Business_pg_login();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void tobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tobackActionPerformed
        // go back
        postgraduate_SB_student_details u = new postgraduate_SB_student_details();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tobackActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TO log out
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void getFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getFnameFocusGained
        if(getFname.getText().equals("first name")){
            getFname.setText("");
        }
    }//GEN-LAST:event_getFnameFocusGained

    private void getFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getFnameFocusLost
        if(getFname.getText().equals("")){
            getFname.setText("first name");
        }
    }//GEN-LAST:event_getFnameFocusLost

    private void getMnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getMnameFocusGained
        if(getMname.getText().equals("middle name")){
            getMname.setText("");
        }
    }//GEN-LAST:event_getMnameFocusGained

    private void getMnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getMnameFocusLost
        if(getMname.getText().equals("")){
            getMname.setText("middle name");
        }
    }//GEN-LAST:event_getMnameFocusLost

    private void getLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getLnameFocusGained
        if(getLname.getText().equals("last name")){
            getLname.setText("");
        }
    }//GEN-LAST:event_getLnameFocusGained

    private void getLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getLnameFocusLost
        if(getLname.getText().equals("")){
            getLname.setText("last name");
        }
    }//GEN-LAST:event_getLnameFocusLost

    private void getNicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getNicFocusGained
        if(getNic.getText().equals("eg:- 983150350v")){
            getNic.setText("");
        }
    }//GEN-LAST:event_getNicFocusGained

    private void getNicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getNicFocusLost
        if(getNic.getText().equals("")){
            getNic.setText("eg:- 983150350v");
        }
    }//GEN-LAST:event_getNicFocusLost

    private void getBdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getBdateFocusGained
        if(getBdate.getText().equals("yyyy-mm-dd")){
            getBdate.setText("");
        }
    }//GEN-LAST:event_getBdateFocusGained

    private void getBdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getBdateFocusLost
        if(getBdate.getText().equals("")){
            getBdate.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_getBdateFocusLost

    private void getAgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAgeFocusGained
        if(getAge.getText().equals("age")){
            getAge.setText("");
        }
    }//GEN-LAST:event_getAgeFocusGained

    private void getAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAgeFocusLost
        if(getAge.getText().equals("")){
            getAge.setText("age");
        }
    }//GEN-LAST:event_getAgeFocusLost

    private void getGenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getGenderFocusGained

        if(getGender.getText().equals("eg:- male")){
            getGender.setText("");
        }
    }//GEN-LAST:event_getGenderFocusGained

    private void getGenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getGenderFocusLost
        if(getGender.getText().equals("")){
            getGender.setText("eg:- male");
        }
    }//GEN-LAST:event_getGenderFocusLost

    private void getPnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getPnumFocusGained
        if(getPnum.getText().equals("eg:- 07x- xxxxxxx")){
            getPnum.setText("");
        }
    }//GEN-LAST:event_getPnumFocusGained

    private void getPnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getPnumFocusLost
        if(getPnum.getText().equals("")){
            getPnum.setText("eg:- 07x- xxxxxxx");
        }
    }//GEN-LAST:event_getPnumFocusLost

    private void getRnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRnumFocusGained
        if(getRnum.getText().equals("eg:- 2018pcs001")){
            getRnum.setText("");
        }
    }//GEN-LAST:event_getRnumFocusGained

    private void getRnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRnumFocusLost
        if(getRnum.getText().equals("")){
            getRnum.setText("eg:- 2018pcs001");
        }
    }//GEN-LAST:event_getRnumFocusLost

    private void getEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getEmailFocusGained
        if(getEmail.getText().equals("yourmail@yourmail.com")){
            getEmail.setText("");
        }
    }//GEN-LAST:event_getEmailFocusGained

    private void getEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getEmailFocusLost
        if(getEmail.getText().equals("")){
            getEmail.setText("yourmail@yourmail.com");
        }
    }//GEN-LAST:event_getEmailFocusLost

    private void getRyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRyearFocusGained
        if(getRyear.getText().equals("year")){
            getRyear.setText("");
        }
    }//GEN-LAST:event_getRyearFocusGained

    private void getRyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRyearFocusLost
         if(getRyear.getText().equals("")){
            getRyear.setText("year");
        }
    }//GEN-LAST:event_getRyearFocusLost

    private void getsemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getsemFocusGained
       if(getsem.getText().equals("eg:- 2018sem01")){
            getsem.setText("");
        }
    }//GEN-LAST:event_getsemFocusGained

    private void getsemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getsemFocusLost
         if(getsem.getText().equals("")){
            getsem.setText("eg:- 2018sem01");
        }
    }//GEN-LAST:event_getsemFocusLost

    private void getCourceIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCourceIdFocusGained
        if(getCourceId.getText().equals("eg:-Mas001")){
            getCourceId.setText("");
        }
    }//GEN-LAST:event_getCourceIdFocusGained

    private void getCourceIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCourceIdFocusLost
         if(getCourceId.getText().equals("")){
            getCourceId.setText("eg:-Mas001");
        }
    }//GEN-LAST:event_getCourceIdFocusLost

    private void getCSub1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub1FocusGained
        if(getCSub1.getText().equals("eg:- PS001")){
            getCSub1.setText("");
        }
    }//GEN-LAST:event_getCSub1FocusGained

    private void getCSub1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub1FocusLost
         if(getCSub1.getText().equals("")){
            getCSub1.setText("eg:- PS001");
        }
    }//GEN-LAST:event_getCSub1FocusLost

    private void getCSub2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub2FocusGained
        if(getCSub2.getText().equals("eg:- PS001")){
            getCSub2.setText("");
        }
    }//GEN-LAST:event_getCSub2FocusGained

    private void getCSub2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub2FocusLost
        if(getCSub2.getText().equals("")){
            getCSub2.setText("eg:- PS001");
        }
    }//GEN-LAST:event_getCSub2FocusLost

    private void getCSub3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub3FocusGained
        if(getCSub3.getText().equals("eg:- PS001")){
            getCSub3.setText("");
        }
    }//GEN-LAST:event_getCSub3FocusGained

    private void getCSub3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub3FocusLost
        if(getCSub3.getText().equals("")){
            getCSub3.setText("eg:- PS001");
        }
    }//GEN-LAST:event_getCSub3FocusLost

    private void getCSub4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub4FocusLost
        if(getCSub4.getText().equals("")){
            getCSub4.setText("eg:- PS001");
        }
    }//GEN-LAST:event_getCSub4FocusLost

    private void getCSub4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub4FocusGained
        if(getCSub4.getText().equals("eg:- PS001")){
            getCSub4.setText("");
        }
    }//GEN-LAST:event_getCSub4FocusGained

    private void getAline1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline1FocusGained
        if(getAline1.getText().equals("line 1")){
            getAline1.setText("");
        }
    }//GEN-LAST:event_getAline1FocusGained

    private void getAline1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline1FocusLost
        if(getAline1.getText().equals("")){
            getAline1.setText("line 1");
        }
    }//GEN-LAST:event_getAline1FocusLost

    private void getAline2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline2FocusGained
        if(getAline2.getText().equals("line 2")){
            getAline2.setText("");
        }
    }//GEN-LAST:event_getAline2FocusGained

    private void getAline2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline2FocusLost
        if(getAline2.getText().equals("")){
            getAline2.setText("line 2");
        }
    }//GEN-LAST:event_getAline2FocusLost

    private void getAline3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline3FocusGained
        if(getAline3.getText().equals("line 3")){
            getAline3.setText("");
        }
    }//GEN-LAST:event_getAline3FocusGained

    private void getAline3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline3FocusLost
       if(getAline3.getText().equals("")){
            getAline3.setText("line 3");
        }
    }//GEN-LAST:event_getAline3FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postgraduate_SB_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_line1;
    private javax.swing.JLabel add_line2;
    private javax.swing.JLabel add_line3;
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel bdate;
    private javax.swing.JDialog comfirm;
    private javax.swing.JLabel complete_year;
    private javax.swing.JLabel courseId2;
    private javax.swing.JPanel details;
    private javax.swing.JLabel email;
    private javax.swing.JLabel f_name;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField getAge;
    private javax.swing.JTextField getAline1;
    private javax.swing.JTextField getAline2;
    private javax.swing.JTextField getAline3;
    private javax.swing.JTextField getBdate;
    private javax.swing.JTextField getCSub1;
    private javax.swing.JTextField getCSub2;
    private javax.swing.JTextField getCSub3;
    private javax.swing.JTextField getCSub4;
    private javax.swing.JTextField getCourceId;
    private javax.swing.JTextField getCyear;
    private javax.swing.JTextField getEmail;
    private javax.swing.JTextField getFname;
    private javax.swing.JTextField getGender;
    private javax.swing.JTextField getInstitute;
    private javax.swing.JTextField getLname;
    private javax.swing.JTextField getMname;
    private javax.swing.JTextField getNic;
    private javax.swing.JTextField getPnum;
    private javax.swing.JTextField getQtype;
    private javax.swing.JTextField getRnum;
    private javax.swing.JTextField getRyear;
    private javax.swing.JTextField getsem;
    private javax.swing.JLabel heading;
    private javax.swing.JButton home;
    private javax.swing.JLabel institute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l_name;
    private javax.swing.JButton logout;
    private javax.swing.JLabel m_name;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nic;
    private javax.swing.JButton ok;
    private javax.swing.JLabel phone_no;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel q_type;
    private javax.swing.JLabel regYear;
    private javax.swing.JLabel reg_no;
    private javax.swing.JLabel semester;
    private javax.swing.JLabel subject;
    private javax.swing.JButton submit;
    private javax.swing.JButton toback;
    // End of variables declaration//GEN-END:variables
}
