
package nsbm.FRAMES.Undergraduateframes.Business_school;

import javax.swing.JOptionPane;
import nsbm.FRAMES.HomeFrames.Home;
import nsbm.objects.DBoperation;
import nsbm.objects.Person;
import nsbm.objects.Student;
import nsbm.objects.UnderGraduate;

/**
 *
 * @author ubandara
 */
public class undergraduate_SB_student extends javax.swing.JFrame {

    DBoperation db = new DBoperation();
    
    public undergraduate_SB_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comfirm = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ok1 = new javax.swing.JButton();
        pic1 = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        Mname = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        Bdate = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        regNo = new javax.swing.JLabel();
        pNo = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        alResult = new javax.swing.JLabel();
        rank = new javax.swing.JLabel();
        getSub2 = new javax.swing.JTextField();
        getSub3 = new javax.swing.JTextField();
        getSub1 = new javax.swing.JTextField();
        getSub4 = new javax.swing.JTextField();
        getSub1result = new javax.swing.JTextField();
        getSub4result = new javax.swing.JTextField();
        getSub2result = new javax.swing.JTextField();
        getSub3result = new javax.swing.JTextField();
        getFname = new javax.swing.JTextField();
        getLname = new javax.swing.JTextField();
        getMname = new javax.swing.JTextField();
        getNic = new javax.swing.JTextField();
        getBdate = new javax.swing.JTextField();
        getAge = new javax.swing.JTextField();
        getRnum = new javax.swing.JTextField();
        getPnum = new javax.swing.JTextField();
        getEmail = new javax.swing.JTextField();
        getRank = new javax.swing.JTextField();
        semester = new javax.swing.JLabel();
        regYear = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        getCSub3 = new javax.swing.JTextField();
        getCourceId = new javax.swing.JTextField();
        getCSub1 = new javax.swing.JTextField();
        getCSub2 = new javax.swing.JTextField();
        getCSub4 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        address = new javax.swing.JLabel();
        Aline1 = new javax.swing.JLabel();
        Aline2 = new javax.swing.JLabel();
        Aline3 = new javax.swing.JLabel();
        getAline3 = new javax.swing.JTextField();
        getAline2 = new javax.swing.JTextField();
        getAline1 = new javax.swing.JTextField();
        alResult1 = new javax.swing.JLabel();
        alResult2 = new javax.swing.JLabel();
        getRyear = new javax.swing.JTextField();
        getsem = new javax.swing.JTextField();
        courseId2 = new javax.swing.JLabel();
        getgender = new javax.swing.JTextField();
        toback = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        home = new javax.swing.JButton();

        comfirm.setTitle("comfirmation");
        comfirm.setLocation(new java.awt.Point(500, 300));
        comfirm.setMinimumSize(new java.awt.Dimension(803, 403));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT  REGISTRATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato", 0, 18))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        jLabel2.setText("REGISTRATION SUCCESSFULLY DONE!!");

        ok1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        ok1.setText("OK");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(ok1)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout comfirmLayout = new javax.swing.GroupLayout(comfirm.getContentPane());
        comfirm.getContentPane().setLayout(comfirmLayout);
        comfirmLayout.setHorizontalGroup(
            comfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comfirmLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        comfirmLayout.setVerticalGroup(
            comfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comfirmLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registration");

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/index.png"))); // NOI18N

        heading.setBackground(java.awt.Color.darkGray);
        heading.setFont(new java.awt.Font("Lato", 1, 80)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("NSBM GREEN UNIVERSITY");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "UNDERGRADUATE STUDENT REGISTRATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lato Light", 1, 20))); // NOI18N

        name.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        name.setText("Name");

        fname.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        fname.setText("First Name");

        Mname.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        Mname.setText("Middle Name");

        lname.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        lname.setText("Last Name");

        nic.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        nic.setText("NIC");

        Bdate.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        Bdate.setText("Birth Date");

        age.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        age.setText("Age");

        gender.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        gender.setText("Gender");

        regNo.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        regNo.setText("Registration No.");

        pNo.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        pNo.setText("Phone No.");

        email.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        email.setText("Email");

        alResult.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        alResult.setText("Grade");

        rank.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        rank.setText("Rank");

        getSub2.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub2.setText("eg:-physics");
        getSub2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub2FocusLost(evt);
            }
        });

        getSub3.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub3.setText("eg:-chemistry");
        getSub3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub3FocusLost(evt);
            }
        });

        getSub1.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub1.setText("eg:-combined maths");
        getSub1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub1FocusLost(evt);
            }
        });

        getSub4.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub4.setText("eg:-english");
        getSub4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub4FocusLost(evt);
            }
        });

        getSub1result.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub1result.setText("eg:-A");
        getSub1result.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub1resultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub1resultFocusLost(evt);
            }
        });

        getSub4result.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub4result.setText("eg:-A");
        getSub4result.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub4resultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub4resultFocusLost(evt);
            }
        });

        getSub2result.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub2result.setText("eg:-A");
        getSub2result.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub2resultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub2resultFocusLost(evt);
            }
        });

        getSub3result.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getSub3result.setText("eg:-A");
        getSub3result.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getSub3resultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getSub3resultFocusLost(evt);
            }
        });

        getFname.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getFname.setText("first name");
        getFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getFnameFocusLost(evt);
            }
        });

        getLname.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getLname.setText("last name");
        getLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getLnameFocusLost(evt);
            }
        });

        getMname.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getMname.setText("middle name");
        getMname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getMnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getMnameFocusLost(evt);
            }
        });

        getNic.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getNic.setText("eg:- 983150350v");
        getNic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getNicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getNicFocusLost(evt);
            }
        });

        getBdate.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getBdate.setText("yyyy-mm-dd");
        getBdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getBdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getBdateFocusLost(evt);
            }
        });

        getAge.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getAge.setText("age");
        getAge.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAgeFocusLost(evt);
            }
        });

        getRnum.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getRnum.setText("eg:- 2018ucs001");
        getRnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getRnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getRnumFocusLost(evt);
            }
        });
        getRnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRnumActionPerformed(evt);
            }
        });

        getPnum.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getPnum.setText("eg:- 07x- xxxxxxx");
        getPnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getPnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getPnumFocusLost(evt);
            }
        });

        getEmail.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getEmail.setText("yourmail@yourmail.com");
        getEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getEmailFocusLost(evt);
            }
        });

        getRank.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getRank.setText("island rank");
        getRank.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getRankFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getRankFocusLost(evt);
            }
        });

        semester.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        semester.setText("semester");

        regYear.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        regYear.setText("Reg. Year");
        regYear.setToolTipText("");

        subject.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        subject.setText("Subject Id");

        getCSub3.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub3.setText("eg:- US001");
        getCSub3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub3FocusLost(evt);
            }
        });

        getCourceId.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCourceId.setText("eg:-Deg001");
        getCourceId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCourceIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCourceIdFocusLost(evt);
            }
        });

        getCSub1.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub1.setText("eg:- US001");
        getCSub1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub1FocusLost(evt);
            }
        });

        getCSub2.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub2.setText("eg:- US001");
        getCSub2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub2FocusLost(evt);
            }
        });

        getCSub4.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getCSub4.setText("eg:- US001");
        getCSub4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getCSub4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getCSub4FocusLost(evt);
            }
        });

        submit.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        address.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        address.setText("Address");

        Aline1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        Aline1.setText("Line 1");

        Aline2.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        Aline2.setText("Line2");

        Aline3.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        Aline3.setText("Line 3");

        getAline3.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getAline3.setText("line 3");
        getAline3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAline3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAline3FocusLost(evt);
            }
        });

        getAline2.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getAline2.setText("line 2");
        getAline2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAline2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAline2FocusLost(evt);
            }
        });

        getAline1.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getAline1.setText("line 1");
        getAline1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getAline1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getAline1FocusLost(evt);
            }
        });

        alResult1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        alResult1.setText("A/L Result");

        alResult2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        alResult2.setText("Subjects");

        getRyear.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getRyear.setText("year");
        getRyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getRyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getRyearFocusLost(evt);
            }
        });

        getsem.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getsem.setText("eg:- 2018sem01");
        getsem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getsemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getsemFocusLost(evt);
            }
        });

        courseId2.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        courseId2.setText("Course Id");

        getgender.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        getgender.setText("eg:- male");
        getgender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                getgenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                getgenderFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alResult2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(alResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(getSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(getSub1result, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getSub3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getSub2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getSub4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getSub3result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getSub4result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getSub2result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(alResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(getLname, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getMname, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getFname)
                                    .addComponent(getNic, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getBdate, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getAge, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getRnum, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getPnum, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(getEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(getRank, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(132, 132, 132)
                                            .addComponent(getgender, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(pNo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(regNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(0, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Aline2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Aline1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Aline3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(getAline2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(getAline3))
                            .addComponent(getAline1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(regYear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(courseId2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(getCourceId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getCSub1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getCSub3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getCSub2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getCSub4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(getRyear, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(getsem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aline1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAline1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getMname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aline2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAline2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aline3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAline3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getNic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getRyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getRnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(getsem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getPnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alResult1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alResult, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alResult2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getSub1result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getSub2result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getSub3result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(getSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(getSub4result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(getRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rank, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getCourceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseId2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getCSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(getCSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        toback.setBackground(java.awt.Color.gray);
        toback.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        toback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/back.png"))); // NOI18N
        toback.setText("BACK");
        toback.setMaximumSize(new java.awt.Dimension(160, 45));
        toback.setMinimumSize(new java.awt.Dimension(160, 45));
        toback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tobackActionPerformed(evt);
            }
        });

        logout.setBackground(java.awt.Color.gray);
        logout.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/logout.png"))); // NOI18N
        logout.setText("LOG OUT");
        logout.setMaximumSize(new java.awt.Dimension(160, 45));
        logout.setMinimumSize(new java.awt.Dimension(160, 45));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        home.setBackground(java.awt.Color.gray);
        home.setFont(new java.awt.Font("Lato", 1, 20)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/home.png"))); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic1)
                        .addGap(82, 82, 82)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toback, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(heading)
                            .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //insert data to database
        try{
            Person P = new Person();
            Student stu1 = new Student();
            UnderGraduate us1 = new UnderGraduate();
        
            us1.setfName(getFname.getText());
            us1.setmName(getMname.getText());
            us1.setlName(getLname.getText());
            us1.setAge(Integer.parseInt(getAge.getText()));
            us1.setNic(getNic.getText());
            us1.setBday(getBdate.getText());
            us1.setSex(getgender.getText());
            us1.setRegNo(getRnum.getText());
            us1.setEmail(email.getText());
            us1.setSemester(getsem.getText());
            us1.setAddressL1(getAline1.getText());
            us1.setAddressL2(getAline1.getText());
            us1.setAddressL3(getAline1.getText());
            us1.setRegYear(getRyear.getText());
            us1.setALsub1(getSub1.getText());
            us1.setALsub2(getSub2.getText());
            us1.setALsub3(getSub3.getText());
            us1.setALsub4(getSub4.getText());
            us1.setALsub1re(getSub1result.getText());
            us1.setALsub2re(getSub2result.getText());
            us1.setALsub3re(getSub3result.getText());
            us1.setALsub4re(getSub4result.getText());
            us1.setRank(getRank.getText());
            us1.setPhone(getPnum.getText());
            us1.setCourseId(getCourceId.getText());
            us1.setFacId("nsbm02");
            us1.setSubId1(getCSub1.getText());
            us1.setSubId2(getCSub2.getText());
            us1.setSubId3(getCSub3.getText());
            us1.setSubId4(getCSub4.getText());
        
        
       
           db.addUndergraduate(us1);
           comfirm.setVisible(true);
       } catch(Exception e){JOptionPane.showMessageDialog(null, "registration failed!!!", "_warning_", JOptionPane.WARNING_MESSAGE);}
        
       
    }//GEN-LAST:event_submitActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
        //
        undergraduate_SB_student_details p = new undergraduate_SB_student_details();
        p.setVisible(true);
        this.dispose();
        comfirm.dispose();
    }//GEN-LAST:event_ok1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TO home
        Business_ug_login a =new Business_ug_login();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void tobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tobackActionPerformed
        // go back
        undergraduate_SB_student_details u = new undergraduate_SB_student_details();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tobackActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TO log out
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void getFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getFnameFocusGained
        if(getFname.getText().equals("first name")){
            getFname.setText("");
        }
    }//GEN-LAST:event_getFnameFocusGained

    private void getFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getFnameFocusLost
        if(getFname.getText().equals("")){
            getFname.setText("first name");
        }
    }//GEN-LAST:event_getFnameFocusLost

    private void getMnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getMnameFocusGained
         if(getMname.getText().equals("middle name")){
            getMname.setText("");
        }
    }//GEN-LAST:event_getMnameFocusGained

    private void getMnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getMnameFocusLost
        if(getMname.getText().equals("")){
            getMname.setText("middle name");
        }
    }//GEN-LAST:event_getMnameFocusLost

    private void getLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getLnameFocusGained
       if(getLname.getText().equals("last name")){
            getLname.setText("");
        }
    }//GEN-LAST:event_getLnameFocusGained

    private void getLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getLnameFocusLost
        if(getLname.getText().equals("")){
            getLname.setText("last name");
        }
    }//GEN-LAST:event_getLnameFocusLost

    private void getNicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getNicFocusGained
        if(getNic.getText().equals("eg:- 983150350v")){
            getNic.setText("");
        }
    }//GEN-LAST:event_getNicFocusGained

    private void getNicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getNicFocusLost
       if(getNic.getText().equals("")){
            getNic.setText("eg:- 983150350v");
        }
    }//GEN-LAST:event_getNicFocusLost

    private void getBdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getBdateFocusGained
        if(getBdate.getText().equals("yyyy-mm-dd")){
            getBdate.setText("");
        }
    }//GEN-LAST:event_getBdateFocusGained

    private void getBdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getBdateFocusLost
        if(getBdate.getText().equals("")){
            getBdate.setText("yyyy-mm-dd");
        }
    }//GEN-LAST:event_getBdateFocusLost

    private void getAgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAgeFocusGained
        if(getAge.getText().equals("age")){
            getAge.setText("");
        }
    }//GEN-LAST:event_getAgeFocusGained

    private void getAgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAgeFocusLost
        if(getAge.getText().equals("")){
            getAge.setText("age");
        }
    }//GEN-LAST:event_getAgeFocusLost

    private void getgenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getgenderFocusGained
        if(getgender.getText().equals("eg:- male")){
            getgender.setText("");
        }
    }//GEN-LAST:event_getgenderFocusGained

    private void getgenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getgenderFocusLost
        if(getgender.getText().equals("")){
            getgender.setText("eg:- male");
        }
    }//GEN-LAST:event_getgenderFocusLost

    private void getRnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRnumFocusGained
        if(getRnum.getText().equals("eg:- 2018ucs001")){
            getRnum.setText("");
        }
    }//GEN-LAST:event_getRnumFocusGained

    private void getRnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRnumFocusLost
       if(getRnum.getText().equals("")){
            getRnum.setText("eg:- 2018ucs001");
        }
    }//GEN-LAST:event_getRnumFocusLost

    private void getPnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getPnumFocusGained
        if(getPnum.getText().equals("eg:- 07x- xxxxxxx")){
            getPnum.setText("");
        }
    }//GEN-LAST:event_getPnumFocusGained

    private void getPnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getPnumFocusLost
        if(getPnum.getText().equals("")){
            getPnum.setText("eg:- 07x- xxxxxxx");
        }
    }//GEN-LAST:event_getPnumFocusLost

    private void getEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getEmailFocusGained
       if(getEmail.getText().equals("yourmail@yourmail.com")){
            getEmail.setText("");
        }
    }//GEN-LAST:event_getEmailFocusGained

    private void getEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getEmailFocusLost
        if(getEmail.getText().equals("")){
            getEmail.setText("yourmail@yourmail.com");
        }
    }//GEN-LAST:event_getEmailFocusLost

    private void getSub1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub1FocusGained
        if(getSub1.getText().equals("eg:-combined maths")){
            getSub1.setText("");
        }
    }//GEN-LAST:event_getSub1FocusGained

    private void getSub1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub1FocusLost
        if(getSub1.getText().equals("")){
            getSub1.setText("eg:-combined maths");
        }
    }//GEN-LAST:event_getSub1FocusLost

    private void getSub2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub2FocusGained
        if(getSub2.getText().equals("eg:-physics")){
            getSub2.setText("");
        }
    }//GEN-LAST:event_getSub2FocusGained

    private void getSub2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub2FocusLost
        if(getSub2.getText().equals("")){
            getSub2.setText("eg:-physics");
        }
    }//GEN-LAST:event_getSub2FocusLost

    private void getSub3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub3FocusGained
        if(getSub3.getText().equals("eg:-chemistry")){
            getSub3.setText("");
         }
    }//GEN-LAST:event_getSub3FocusGained

    private void getSub3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub3FocusLost
        if(getSub3.getText().equals("")){
            getSub3.setText("eg:-chemistry");
        }
    }//GEN-LAST:event_getSub3FocusLost

    private void getSub4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub4FocusGained
        if(getSub4.getText().equals("eg:-english")){
            getSub4.setText("");
         }
    }//GEN-LAST:event_getSub4FocusGained

    private void getSub4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub4FocusLost
        if(getSub4.getText().equals("")){
            getSub4.setText("eg:-english");
        }
    }//GEN-LAST:event_getSub4FocusLost

    private void getSub1resultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub1resultFocusGained
        if(getSub1result.getText().equals("eg:-A")){
            getSub1result.setText("");
        }
    }//GEN-LAST:event_getSub1resultFocusGained

    private void getSub1resultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub1resultFocusLost
        if(getSub1result.getText().equals("")){
            getSub1result.setText("eg:-A");
        }
    }//GEN-LAST:event_getSub1resultFocusLost

    private void getSub2resultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub2resultFocusGained
         if(getSub2result.getText().equals("eg:-A")){
            getSub2result.setText("");
        }
    }//GEN-LAST:event_getSub2resultFocusGained

    private void getSub2resultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub2resultFocusLost
        if(getSub2result.getText().equals("")){
            getSub2result.setText("eg:-A");
        }
    }//GEN-LAST:event_getSub2resultFocusLost

    private void getSub3resultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub3resultFocusGained
         if(getSub3result.getText().equals("eg:-A")){
            getSub3result.setText("");
         }
    }//GEN-LAST:event_getSub3resultFocusGained

    private void getSub3resultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub3resultFocusLost
        if(getSub3result.getText().equals("")){
            getSub3result.setText("eg:-A");
        }
    }//GEN-LAST:event_getSub3resultFocusLost

    private void getSub4resultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub4resultFocusGained
        if(getSub4result.getText().equals("eg:-A")){
            getSub4result.setText("");
         }
    }//GEN-LAST:event_getSub4resultFocusGained

    private void getSub4resultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getSub4resultFocusLost
        if(getSub4result.getText().equals("")){
            getSub4result.setText("eg:-A");
        }
    }//GEN-LAST:event_getSub4resultFocusLost

    private void getRankFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRankFocusGained
         if(getRank.getText().equals("island rank")){
            getRank.setText("");
         }
    }//GEN-LAST:event_getRankFocusGained

    private void getRankFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRankFocusLost
         if(getRank.getText().equals("")){
            getRank.setText("island rank");
         }
    }//GEN-LAST:event_getRankFocusLost

    private void getAline1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline1FocusGained
        if(getAline1.getText().equals("line 1")){
            getAline1.setText("");
        }
    }//GEN-LAST:event_getAline1FocusGained

    private void getAline1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline1FocusLost
        if(getAline1.getText().equals("")){
            getAline1.setText("line 1");
        }
    }//GEN-LAST:event_getAline1FocusLost

    private void getAline2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline2FocusGained
        if(getAline2.getText().equals("line 2")){
            getAline2.setText("");
        }
    }//GEN-LAST:event_getAline2FocusGained

    private void getAline2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline2FocusLost
        if(getAline2.getText().equals("")){
            getAline2.setText("line 2");
        }
    }//GEN-LAST:event_getAline2FocusLost

    private void getAline3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline3FocusGained
        if(getAline3.getText().equals("line 3")){
            getAline3.setText("");
        }
    }//GEN-LAST:event_getAline3FocusGained

    private void getAline3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getAline3FocusLost
        if(getAline3.getText().equals("")){
            getAline3.setText("line 3");
        }
    }//GEN-LAST:event_getAline3FocusLost

    private void getRyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRyearFocusGained
        if(getRyear.getText().equals("year")){
            getRyear.setText("");
        }
    }//GEN-LAST:event_getRyearFocusGained

    private void getRyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getRyearFocusLost
        if(getRyear.getText().equals("")){
            getRyear.setText("year");
        }
    }//GEN-LAST:event_getRyearFocusLost

    private void getsemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getsemFocusGained
        if(getsem.getText().equals("eg:- 2018sem01")){
            getsem.setText("");
        }
    }//GEN-LAST:event_getsemFocusGained

    private void getsemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getsemFocusLost
        if(getsem.getText().equals("")){
            getsem.setText("eg:- 2018sem01");
        }
    }//GEN-LAST:event_getsemFocusLost

    private void getCourceIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCourceIdFocusGained
        if(getCourceId.getText().equals("eg:-Deg001")){
            getCourceId.setText("");
        }
    }//GEN-LAST:event_getCourceIdFocusGained

    private void getCourceIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCourceIdFocusLost
        if(getCourceId.getText().equals("eg:-Deg001")){
            getCourceId.setText("");
        }
    }//GEN-LAST:event_getCourceIdFocusLost

    private void getCSub1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub1FocusGained
        if(getCSub1.getText().equals("eg:- US001")){
            getCSub1.setText("");
        }
    }//GEN-LAST:event_getCSub1FocusGained

    private void getCSub1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub1FocusLost
        if(getCSub1.getText().equals("")){
            getCSub1.setText("eg:- US001");
        }
    }//GEN-LAST:event_getCSub1FocusLost

    private void getCSub2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub2FocusGained
        if(getCSub2.getText().equals("eg:- US001")){
            getCSub2.setText("");
        }
    }//GEN-LAST:event_getCSub2FocusGained

    private void getCSub2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub2FocusLost
        if(getCSub2.getText().equals("")){
            getCSub2.setText("eg:- US001");
        }
    }//GEN-LAST:event_getCSub2FocusLost

    private void getCSub3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub3FocusGained
        if(getCSub3.getText().equals("eg:- US001")){
            getCSub3.setText("");
        }
    }//GEN-LAST:event_getCSub3FocusGained

    private void getCSub3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub3FocusLost
        if(getCSub3.getText().equals("")){
            getCSub3.setText("eg:- US001");
        }
    }//GEN-LAST:event_getCSub3FocusLost

    private void getCSub4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub4FocusGained
        if(getCSub4.getText().equals("eg:- US001")){
            getCSub4.setText("");
        }
    }//GEN-LAST:event_getCSub4FocusGained

    private void getCSub4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_getCSub4FocusLost
        if(getCSub4.getText().equals("")){
            getCSub4.setText("eg:- US001");
        }
    }//GEN-LAST:event_getCSub4FocusLost

    private void getRnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getRnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(undergraduate_SB_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(undergraduate_SB_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(undergraduate_SB_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(undergraduate_SB_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new undergraduate_SB_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aline1;
    private javax.swing.JLabel Aline2;
    private javax.swing.JLabel Aline3;
    private javax.swing.JLabel Bdate;
    private javax.swing.JLabel Mname;
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel alResult;
    private javax.swing.JLabel alResult1;
    private javax.swing.JLabel alResult2;
    private javax.swing.JDialog comfirm;
    private javax.swing.JLabel courseId2;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel gender;
    private javax.swing.JTextField getAge;
    private javax.swing.JTextField getAline1;
    private javax.swing.JTextField getAline2;
    private javax.swing.JTextField getAline3;
    private javax.swing.JTextField getBdate;
    private javax.swing.JTextField getCSub1;
    private javax.swing.JTextField getCSub2;
    private javax.swing.JTextField getCSub3;
    private javax.swing.JTextField getCSub4;
    private javax.swing.JTextField getCourceId;
    private javax.swing.JTextField getEmail;
    private javax.swing.JTextField getFname;
    private javax.swing.JTextField getLname;
    private javax.swing.JTextField getMname;
    private javax.swing.JTextField getNic;
    private javax.swing.JTextField getPnum;
    private javax.swing.JTextField getRank;
    private javax.swing.JTextField getRnum;
    private javax.swing.JTextField getRyear;
    private javax.swing.JTextField getSub1;
    private javax.swing.JTextField getSub1result;
    private javax.swing.JTextField getSub2;
    private javax.swing.JTextField getSub2result;
    private javax.swing.JTextField getSub3;
    private javax.swing.JTextField getSub3result;
    private javax.swing.JTextField getSub4;
    private javax.swing.JTextField getSub4result;
    private javax.swing.JTextField getgender;
    private javax.swing.JTextField getsem;
    private javax.swing.JLabel heading;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lname;
    private javax.swing.JButton logout;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nic;
    private javax.swing.JButton ok1;
    private javax.swing.JLabel pNo;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel rank;
    private javax.swing.JLabel regNo;
    private javax.swing.JLabel regYear;
    private javax.swing.JLabel semester;
    private javax.swing.JLabel subject;
    private javax.swing.JButton submit;
    private javax.swing.JButton toback;
    // End of variables declaration//GEN-END:variables
}
