
package nsbm.FRAMES.Administrator;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import nsbm.FRAMES.HomeFrames.Home;

/**
 *
 * @author ubandara
 */
public class admin_Details extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public admin_Details() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        faculty = new javax.swing.JButton();
        facultyAdmin = new javax.swing.JButton();
        instructors = new javax.swing.JButton();
        lectures = new javax.swing.JButton();
        change_admin_details = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("admin_Details");

        heading.setBackground(java.awt.Color.darkGray);
        heading.setFont(new java.awt.Font("Lato", 1, 80)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("NSBM GREEN UNIVERSITY");

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nsbm/images/index.png"))); // NOI18N

        faculty.setBackground(java.awt.Color.darkGray);
        faculty.setFont(new java.awt.Font("Lato", 0, 48)); // NOI18N
        faculty.setForeground(new java.awt.Color(254, 254, 254));
        faculty.setText("FACULTY");
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });

        facultyAdmin.setBackground(java.awt.Color.darkGray);
        facultyAdmin.setFont(new java.awt.Font("Lato", 0, 48)); // NOI18N
        facultyAdmin.setForeground(new java.awt.Color(254, 254, 254));
        facultyAdmin.setText("FACULTY ADMIN");
        facultyAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyAdminActionPerformed(evt);
            }
        });

        instructors.setBackground(java.awt.Color.gray);
        instructors.setFont(new java.awt.Font("Lato", 0, 48)); // NOI18N
        instructors.setText("INSTRUCTORS");
        instructors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorsActionPerformed(evt);
            }
        });

        lectures.setBackground(java.awt.Color.gray);
        lectures.setFont(new java.awt.Font("Lato", 0, 48)); // NOI18N
        lectures.setText("LECTURES");
        lectures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturesActionPerformed(evt);
            }
        });

        change_admin_details.setBackground(java.awt.Color.darkGray);
        change_admin_details.setFont(new java.awt.Font("Lato", 0, 48)); // NOI18N
        change_admin_details.setForeground(new java.awt.Color(254, 254, 254));
        change_admin_details.setText("CHANGE  ADMINISTRTOR  DETAILS");
        change_admin_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_admin_detailsActionPerformed(evt);
            }
        });

        logout.setBackground(java.awt.Color.darkGray);
        logout.setFont(new java.awt.Font("Lato", 0, 36)); // NOI18N
        logout.setForeground(new java.awt.Color(254, 254, 254));
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pic1)
                .addGap(79, 79, 79)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(566, 566, 566))
            .addGroup(layout.createSequentialGroup()
                .addGap(582, 582, 582)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lectures, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instructors, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(change_admin_details, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                        .addComponent(facultyAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(heading)))
                .addGap(73, 73, 73)
                .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lectures, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructors, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(facultyAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(change_admin_details, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // faculty details
        try {
            Faculty_details f = new  Faculty_details();
            f.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(admin_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_facultyActionPerformed

    private void lecturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturesActionPerformed
        // Lecture details
       Lecture_details l = new  Lecture_details();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lecturesActionPerformed

    private void InstructorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorsActionPerformed
        // instructor details
       
            Instructor_details i = new  Instructor_details();
            i.setVisible(true);
            this.dispose();
        
        /*Instructor_details i = new  Instructor_details();
        i.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_InstructorsActionPerformed

    private void facultyAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyAdminActionPerformed
        // faculty admin
        try {
                Faculty_admin_details a = new  Faculty_admin_details(); 
                a.setVisible(true);
                this.dispose();
             
       } catch (SQLException ex) {
            Logger.getLogger(admin_Details.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_facultyAdminActionPerformed

    private void change_admin_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_admin_detailsActionPerformed
        // admin details
        changeAdminstrationDetails c = new  changeAdminstrationDetails();
        c.setVisible(true);
    }//GEN-LAST:event_change_admin_detailsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // log out
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton change_admin_details;
    private javax.swing.JButton faculty;
    private javax.swing.JButton facultyAdmin;
    private javax.swing.JLabel heading;
    private javax.swing.JButton instructors;
    private javax.swing.JButton lectures;
    private javax.swing.JButton logout;
    private javax.swing.JLabel pic1;
    // End of variables declaration//GEN-END:variables
}
